smallsh: smallsh.c background_processes.c command_executor.c command_parser.c signal_handlers.c global.c
	gcc -std=c99 -o smallsh smallsh.c background_processes.c command_executor.c command_parser.c signal_handlers.c global.c
